# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


Hack.create(entry: "mouseover")
Hack.create(entry: "Angular")
Hack.create(entry: "Pagination")
Hack.create(entry: "Rails is amazing")

Hack.create(entry: "moodswings")
Hack.create(entry: "ApplicationController")
Hack.create(entry: "autocomplete")
Hack.create(entry: "initialize")
Hack.create(entry: "event listener")
Hack.create(entry: "geolocation")
Hack.create(entry: "event.preventDefault")
Hack.create(entry: "consolelog")
Hack.create(entry: "getElementById")
Hack.create(entry: "git push origin master")
Hack.create(entry: "setPosition")
Hack.create(entry: "variables")

Hack.create(entry: "debugger")
Hack.create(entry: "placeholder")
Hack.create(entry: "infowindow") 
Hack.create(entry: "codepen")
Hack.create(entry: "$scope")
Hack.create(entry: "heroku")
Hack.create(entry: "general assembly")
Hack.create(entry: "github")
Hack.create(entry: "google chrome")
Hack.create(entry: "responsive")
Hack.create(entry: "bootstrap")
Hack.create(entry: "amazeballs")
Hack.create(entry: "database")
Hack.create(entry: "ajax")
Hack.create(entry: "google maps")
Hack.create(entry: "rake routes")
Hack.create(entry: "console.log")
Hack.create(entry: "honhonhon")
Hack.create(entry: "boom")

Hack.create(entry: "mandrill")
Hack.create(entry: "hipchat")
Hack.create(entry: "ActiveRecord")
Hack.create(entry: "CarrierWave")
Hack.create(entry: "postgresql")
Hack.create(entry: "unicode")
Hack.create(entry: "associations")
Hack.create(entry: "nested ")
Hack.create(entry: "wireframe")
Hack.create(entry: "site map")
Hack.create(entry: "user journey")
Hack.create(entry: "rails g scaffold")
Hack.create(entry: "mockups")
Hack.create(entry: "model diagram")
Hack.create(entry: "pagination")
Hack.create(entry: "attr accessor")
Hack.create(entry: "code academy")
Hack.create(entry: "refactoring")
Hack.create(entry: "test driven development")
Hack.create(entry: "ruby on rails")
Hack.create(entry: "pry byebug")
Hack.create(entry: "sublime")
Hack.create(entry: "terminal")
Hack.create(entry: "stackoverflow")
Hack.create(entry: "railscast")
Hack.create(entry: "has many through")
Hack.create(entry: "code golf")
Hack.create(entry: "sinatra")
Hack.create(entry: "binary")
Hack.create(entry: "authentication")
Hack.create(entry: "authorisation")
Hack.create(entry: "Hypertext Transfer Protocol")
Hack.create(entry: "Document Object Model")
Hack.create(entry: "Cascading Style Sheets")
Hack.create(entry: "asynchronous JavaScript + XM")